const PDFDocument = require("pdfkit");
const path = require("path");
const Income = require("../models/Income");
const Expense = require("../models/Expense");

exports.generateReport = async (req, res) => {
  try {
    const userId = req.user;
    const { type, month, year } = req.query;

    const startDate =
      type === "monthly"
        ? new Date(year, month - 1, 1)
        : new Date(year, 0, 1);

    const endDate =
      type === "monthly"
        ? new Date(year, month, 0, 23, 59, 59)
        : new Date(year, 11, 31, 23, 59, 59);

    const incomes = await Income.find({
      user: userId,
      date: { $gte: startDate, $lte: endDate }
    });

    const expenses = await Expense.find({
      user: userId,
      date: { $gte: startDate, $lte: endDate }
    });

    const totalIncome = incomes.reduce((a, b) => a + b.amount, 0);
    const totalExpense = expenses.reduce((a, b) => a + b.amount, 0);
    const savings = totalIncome - totalExpense;

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=TaxPal_${type}_Report.pdf`
    );

    doc.pipe(res);

    /* ===== BRANDING HEADER ===== */
    const logoPath = path.join(__dirname, "../assets/logo.png");

    doc.image(logoPath, 50, 40, { width: 60 });
    doc
      .fontSize(20)
      .fillColor("#1e3c72")
      .text("TaxPal Financial Report", 130, 50);

    doc
      .fontSize(12)
      .fillColor("gray")
      .text(
        type === "monthly"
          ? `Month: ${month}/${year}`
          : `Year: ${year}`,
        130,
        75
      );

    doc.moveDown(3);

    /* ===== SUMMARY ===== */
    doc.fillColor("black").fontSize(14);
    doc.text(`Total Income: ₹${totalIncome}`);
    doc.text(`Total Expenses: ₹${totalExpense}`);
    doc.text(`Net Savings: ₹${savings}`);
    doc.moveDown();

    /* ===== INCOME ===== */
    doc.fontSize(16).text("Income Details");
    doc.moveDown(0.5);
    incomes.forEach((i) =>
      doc.fontSize(12).text(`₹${i.amount} - ${i.source || "N/A"}`)
    );

    doc.moveDown();

    /* ===== EXPENSE ===== */
    doc.fontSize(16).text("Expense Details");
    doc.moveDown(0.5);
    expenses.forEach((e) =>
      doc.fontSize(12).text(`₹${e.amount} - ${e.category || "N/A"}`)
    );

    /* ===== FOOTER ===== */
    doc
      .fontSize(10)
      .fillColor("gray")
      .text(
        "Generated by TaxPal • Smart Finance for Freelancers",
        50,
        doc.page.height - 50,
        { align: "center" }
      );

    doc.end();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};